{% set name = "fsl-sub-plugin-slurm" %}
{% set version = "1.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fsl_sub_plugin_slurm-{{ version }}.tar.gz
  sha256: db0dd6309afdf6f3329d613c2cb0d2a57e1078d0ab5f6eb2cafff9de5d1bd215

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - fsl-sub >=2.8.0
    - ruamel.yaml >=0.16.7

test:
  imports:
    - fsl_sub_plugin_slurm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://git.fmrib.ox.ac.uk/fsl/fsl_sub_plugin_slurm
  summary: FSL Cluster Submission Plugin for Slurm
  dev_url: https://git.fmrib.ox.ac.uk/fsl/fsl_sub_plugin_slurm
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pauldmccarthy
